# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               hacktagon
tagline:             'Shall we play a game?'
description:         'we are made up of muk piece'
url:                 https://hacktagon.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              hacktagon
  url:               https://twitter.com/hacktagon
  email:             hacktagon.kr@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/hacktagon
twitter:			http://twitter.com/hacktagon
disqus:       hacktagon

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:         https://github.com/ariestiyansyah/naringu
